// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNcp19rZCco2zmjdjC1CkYQtp8tvBen-0',
    appId: '1:275535450956:web:fea0603d46ee33027db5e9',
    messagingSenderId: '275535450956',
    projectId: 'finance-app-6bbc9',
    authDomain: 'finance-app-6bbc9.firebaseapp.com',
    storageBucket: 'finance-app-6bbc9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiC4Kb7HHGi9ZPYqHENuU6lVp-qQsYAGs',
    appId: '1:275535450956:android:094f8df5928f207c7db5e9',
    messagingSenderId: '275535450956',
    projectId: 'finance-app-6bbc9',
    storageBucket: 'finance-app-6bbc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Ax4F2z4q-YLIpaLErUqHZSjYqCScoPQ',
    appId: '1:275535450956:ios:f823c17a6947d4287db5e9',
    messagingSenderId: '275535450956',
    projectId: 'finance-app-6bbc9',
    storageBucket: 'finance-app-6bbc9.firebasestorage.app',
    iosBundleId: 'com.example.bagFlow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Ax4F2z4q-YLIpaLErUqHZSjYqCScoPQ',
    appId: '1:275535450956:ios:f823c17a6947d4287db5e9',
    messagingSenderId: '275535450956',
    projectId: 'finance-app-6bbc9',
    storageBucket: 'finance-app-6bbc9.firebasestorage.app',
    iosBundleId: 'com.example.bagFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNcp19rZCco2zmjdjC1CkYQtp8tvBen-0',
    appId: '1:275535450956:web:6715c861a6e9cc287db5e9',
    messagingSenderId: '275535450956',
    projectId: 'finance-app-6bbc9',
    authDomain: 'finance-app-6bbc9.firebaseapp.com',
    storageBucket: 'finance-app-6bbc9.firebasestorage.app',
  );

}